project_id = "aohrfehhyjdebaatzqdl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.analyze-cv-with-ai]
verify_jwt = true

[functions.adobe-pdf-extract]
verify_jwt = true

[functions.adobe-background-process]
verify_jwt = false

[functions.send-usage-alert]
verify_jwt = false

[functions.process-adobe-queue]
verify_jwt = false