import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { 
  Pagination, 
  PaginationContent, 
  PaginationItem, 
  PaginationLink, 
  PaginationNext, 
  PaginationPrevious 
} from '@/components/ui/pagination';
import { History, MessageSquare, Calendar, Building, Eye, Download, Trash2, Target, FileText, Plus, Search } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import LinkageIndicators from '@/components/analysis/LinkageIndicators';
import { DocumentTypeBadge } from '@/components/ui/document-type-badge';

interface InterviewPrepItem {
  id: string;
  job_title: string;
  company_name: string;
  content: string;
  created_at: string;
  updated_at: string;
  generation_parameters?: any;
  regeneration_count?: number;
  analysis_result_id?: string;
  linked_cover_letter_id?: string;
}

interface InterviewPrepHistoryProps {
  onSelectInterviewPrep?: (interviewPrep: InterviewPrepItem) => void;
  className?: string;
}

const InterviewPrepHistory: React.FC<InterviewPrepHistoryProps> = ({
  onSelectInterviewPrep,
  className = ''
}) => {
  const { user } = useAuth();
  const [interviewPreps, setInterviewPreps] = useState<InterviewPrepItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [linkageCache, setLinkageCache] = useState<Record<string, any>>({});
  const [searchQuery, setSearchQuery] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const { toast } = useToast();
  const navigate = useNavigate();

  useEffect(() => {
    fetchInterviewPrepHistory();
  }, []);

  const fetchInterviewPrepHistory = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        setIsLoading(false);
        return;
      }

      const { data, error } = await supabase
        .from('interview_prep')
        .select(`
          *,
          analysis_result_id,
          linked_cover_letter_id
        `)
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })
        .limit(20);

      if (error) {
        console.error('Error fetching interview prep history:', error);
        toast({
          title: "Error Loading History",
          description: "Failed to load your interview prep history.",
          variant: "destructive"
        });
      } else {
        setInterviewPreps(data || []);
      }
    } catch (error) {
      console.error('Unexpected error:', error);
      toast({
        title: "Error Loading History",
        description: "An unexpected error occurred while loading your history.",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleView = (interviewPrep: InterviewPrepItem) => {
    if (onSelectInterviewPrep) {
      onSelectInterviewPrep(interviewPrep);
    }
  };

  const handleDownload = (interviewPrep: InterviewPrepItem) => {
    try {
      const content = `INTERVIEW PREPARATION NOTES
==================

Job Title: ${interviewPrep.job_title}
Company: ${interviewPrep.company_name}
Date: ${new Date(interviewPrep.created_at).toLocaleDateString()}

${interviewPrep.content}

---
Generated by TuneMyCV - Your AI-Powered Career Assistant`;

      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Interview_Prep_${interviewPrep.job_title}_${interviewPrep.company_name}_${new Date(interviewPrep.created_at).toISOString().split('T')[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Download failed:', error);
      toast({
        title: "Download Failed",
        description: "Failed to download the interview prep.",
        variant: "destructive"
      });
    }
  };

  const handleDelete = async (interviewPrep: InterviewPrepItem) => {
    if (!window.confirm(`Are you sure you want to delete this interview prep? This action cannot be undone.`)) {
      return;
    }

    setDeletingId(interviewPrep.id);

    try {
      const { error } = await supabase
        .from('interview_prep')
        .delete()
        .eq('id', interviewPrep.id)
        .eq('user_id', user?.id);

      if (error) throw error;

      setInterviewPreps(prev => prev.filter(item => item.id !== interviewPrep.id));
      toast({
        title: "Interview Prep Deleted",
        description: "The interview prep has been successfully deleted.",
      });
    } catch (error) {
      console.error('Delete failed:', error);
      toast({
        title: "Delete Failed",
        description: "Failed to delete the interview prep. Please try again.",
        variant: "destructive"
      });
    } finally {
      setDeletingId(null);
    }
  };

  const handleViewAnalysis = (analysisId: string) => {
    navigate('/analyze', {
      state: {
        viewAnalysis: analysisId
      }
    });
  };

  const handleViewCoverLetter = (coverLetterId: string) => {
    navigate(`/cover-letter?id=${coverLetterId}`);
  };

  const handleCreateCoverLetter = (interviewPrep: InterviewPrepItem) => {
    navigate('/cover-letter', {
      state: {
        fromInterviewPrep: true,
        interviewPrepData: interviewPrep
      }
    });
  };

  // Load linkage data for interview preps
  useEffect(() => {
    if (interviewPreps.length > 0) {
      const loadLinkages = async () => {
        const linkages: Record<string, any> = {};
        for (const interviewPrep of interviewPreps) {
          const linkage = {
            hasLinkedAnalysis: !!interviewPrep.analysis_result_id,
            hasLinkedCoverLetter: !!interviewPrep.linked_cover_letter_id,
            linkedAnalysisId: interviewPrep.analysis_result_id,
            linkedCoverLetterId: interviewPrep.linked_cover_letter_id
          };
          linkages[interviewPrep.id] = linkage;
        }
        setLinkageCache(linkages);
      };
      loadLinkages();
    }
  }, [interviewPreps]);

  // Filter and search logic
  const filteredInterviewPreps = interviewPreps.filter(interviewPrep => {
    const matchesSearch = searchQuery === '' || 
      (interviewPrep.job_title || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
      (interviewPrep.company_name || '').toLowerCase().includes(searchQuery.toLowerCase());
    return matchesSearch;
  });

  // Pagination logic
  const totalPages = Math.ceil(filteredInterviewPreps.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const paginatedInterviewPreps = filteredInterviewPreps.slice(startIndex, endIndex);

  // Reset to first page when search or items per page changes
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, itemsPerPage]);

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (isLoading) {
    return (
      <div className={className}>
        <div className="flex items-center justify-center py-8">
          <div className="text-center space-y-4">
            <History className="h-8 w-8 animate-pulse mx-auto text-primary" />
            <p className="text-muted-foreground">Loading your interview prep history...</p>
          </div>
        </div>
      </div>
    );
  }

  if (interviewPreps.length === 0) {
    return (
      <div className={className}>
        <div className="mb-6">
          <h2 className="text-title font-bold flex items-center gap-2">
            <History className="h-5 w-5 text-primary" />
            Interview Prep History
          </h2>
        </div>
        <div className="text-center py-8">
          <History className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">
            No Interview Preps
          </h3>
          <p className="text-gray-600 dark:text-gray-400">
            Your generated interview prep notes will appear here.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className={className}>
      <div className="mb-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-title font-bold flex items-center gap-2">
            <History className="h-5 w-5 text-primary" />
            Interview Prep History
          </h2>
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <Search className="h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search interview preps..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-64"
              />
            </div>
            {filteredInterviewPreps.length > 0 && (
              <div className="flex items-center space-x-2">
                <span className="text-caption text-muted-foreground">Show:</span>
                <Select value={itemsPerPage.toString()} onValueChange={(value) => setItemsPerPage(Number(value))}>
                  <SelectTrigger className="w-20">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="10">10</SelectItem>
                    <SelectItem value="20">20</SelectItem>
                    <SelectItem value="30">30</SelectItem>
                  </SelectContent>
                </Select>
                <span className="text-caption text-muted-foreground">per page</span>
              </div>
            )}
          </div>
        </div>
      </div>
      <div className="space-y-4">
        {paginatedInterviewPreps.map((interviewPrep) => (
          <Card
            key={interviewPrep.id}
            className="hover:shadow-md transition-all duration-200 hover:border-primary/50 hover:bg-muted/50 cursor-pointer border border-border relative"
            onClick={() => handleView(interviewPrep)}
          >
            {/* Document Type Badge */}
            <DocumentTypeBadge 
              type="interview_prep" 
              variant="secondary" 
              size="sm" 
              className="absolute top-2 right-2"
            />
            
            <CardContent className="p-6">
              <div className="flex justify-between items-start mb-4">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <h3 className="text-heading font-medium text-foreground">
                      {interviewPrep.job_title}
                    </h3>
                    <Badge variant="compact" className="text-tiny">
                      Interview Prep
                    </Badge>
                  </div>
                  
                  <div className="flex items-center space-x-4 text-caption text-muted-foreground mb-2">
                    <div className="flex items-center space-x-1">
                      <Building className="h-3 w-3" />
                      <span>{interviewPrep.company_name}</span>
                    </div>
                    <div className="flex items-center space-x-1">
                      <Calendar className="h-3 w-3" />
                      <span>Updated {formatDate(interviewPrep.updated_at)}</span>
                    </div>
                    {interviewPrep.regeneration_count && interviewPrep.regeneration_count > 0 && (
                      <div className="text-primary font-medium">
                        Regenerated {interviewPrep.regeneration_count} time{interviewPrep.regeneration_count > 1 ? 's' : ''}
                      </div>
                    )}
                  </div>
                  
                  {/* Linkage Indicators */}
                  <div className="mt-2">
                    <LinkageIndicators
                      hasLinkedCoverLetter={linkageCache[interviewPrep.id]?.hasLinkedCoverLetter || false}
                      hasLinkedInterviewPrep={false}
                      onViewCoverLetter={() => handleViewCoverLetter(linkageCache[interviewPrep.id]?.linkedCoverLetterId)}
                      compact={true}
                    />
                  </div>
                </div>
              </div>

              {/* Action buttons row at bottom - reduced spacing by 50% and matching design */}
              <div className="flex items-center justify-between pt-1.5 border-t border-border">
                {/* Dynamic CTAs on the left */}
                <div className="flex items-center space-x-2">
                  {/* View Source Analysis CTA */}
                  {linkageCache[interviewPrep.id]?.hasLinkedAnalysis && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleViewAnalysis(linkageCache[interviewPrep.id].linkedAnalysisId);
                      }}
                      className="text-caption font-medium transition-colors h-8 px-3 text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
                    >
                      <Target className="h-4 w-4 mr-2" />
                      View Source Analysis
                    </Button>
                  )}

                  {/* Dynamic CTA Logic for Cover Letter */}
                  {linkageCache[interviewPrep.id]?.hasLinkedCoverLetter ? (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleViewCoverLetter(linkageCache[interviewPrep.id].linkedCoverLetterId);
                      }}
                      className="text-caption font-medium transition-colors h-8 px-3 text-green-600 hover:text-green-700 dark:text-green-400 dark:hover:text-green-300"
                    >
                      <FileText className="h-4 w-4 mr-2" />
                      View Cover Letter
                    </Button>
                  ) : (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleCreateCoverLetter(interviewPrep);
                      }}
                      className="text-caption font-medium transition-colors h-8 px-3 text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
                    >
                      <Plus className="h-4 w-4 mr-2" />
                      Generate Cover Letter
                    </Button>
                  )}
                </div>

                {/* Action icons on the right - matching spacing */}
                <div className="flex items-center space-x-6">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleView(interviewPrep);
                    }}
                    className="text-caption font-medium transition-colors h-8 px-3 flex items-center space-x-2 text-black hover:text-black"
                  >
                    <Eye className="h-4 w-4 text-black" />
                    <span>View</span>
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDownload(interviewPrep);
                    }}
                    className="text-caption font-medium transition-colors h-8 px-3 flex items-center space-x-2 text-black hover:text-black"
                  >
                    <Download className="h-4 w-4 text-black" />
                    <span>Download</span>
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDelete(interviewPrep);
                    }}
                    disabled={deletingId === interviewPrep.id}
                    className="text-caption font-medium transition-colors h-8 px-3 flex items-center space-x-2 text-destructive hover:text-destructive hover:bg-destructive/10"
                  >
                    <Trash2 className="h-4 w-4" />
                    <span>Delete</span>
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="mt-6 flex justify-center">
          <Pagination>
            <PaginationContent>
              <PaginationItem>
                <PaginationPrevious 
                  href="#" 
                  onClick={(e) => {
                    e.preventDefault();
                    if (currentPage > 1) setCurrentPage(currentPage - 1);
                  }}
                  className={currentPage <= 1 ? "pointer-events-none opacity-50" : ""}
                />
              </PaginationItem>
              
              {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
                <PaginationItem key={page}>
                  <PaginationLink
                    href="#"
                    onClick={(e) => {
                      e.preventDefault();
                      setCurrentPage(page);
                    }}
                    isActive={currentPage === page}
                  >
                    {page}
                  </PaginationLink>
                </PaginationItem>
              ))}
              
              <PaginationItem>
                <PaginationNext 
                  href="#" 
                  onClick={(e) => {
                    e.preventDefault();
                    if (currentPage < totalPages) setCurrentPage(currentPage + 1);
                  }}
                  className={currentPage >= totalPages ? "pointer-events-none opacity-50" : ""}
                />
              </PaginationItem>
            </PaginationContent>
          </Pagination>
        </div>
      )}
    </div>
  );
};

export default InterviewPrepHistory;