
import React from 'react';
import { ArrowLeft, Download, BarChart3, CheckCircle, XCircle, TrendingUp, Star, AlertCircle, Target, BookOpen, Users } from 'lucide-react';
import { Progress } from '@/components/ui/progress';

interface AnalysisResultsProps {
  result: any;
  onStartNew: () => void;
}

const AnalysisResults: React.FC<AnalysisResultsProps> = ({ result, onStartNew }) => {
  const getScoreColor = (score: number) => {
    if (score >= 70) return 'text-green-600';
    if (score >= 40) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getScoreBgColor = (score: number) => {
    if (score >= 70) return 'bg-green-50 border-green-200';
    if (score >= 40) return 'bg-yellow-50 border-yellow-200';
    return 'bg-red-50 border-red-200';
  };

  const downloadPDF = () => {
    // Create a comprehensive report content
    const reportContent = `
CV COMPATIBILITY ANALYSIS REPORT

Job Title: ${result.job_title || 'Not specified'}
Company: ${result.company_name || 'Not specified'}
Analysis Date: ${new Date(result.created_at).toLocaleDateString()}

COMPATIBILITY SCORE: ${result.compatibility_score}%

EXECUTIVE SUMMARY:
${result.executive_summary || 'No summary available'}

STRENGTHS:
${result.strengths?.map((strength: string, index: number) => `${index + 1}. ${strength}`).join('\n') || 'No strengths identified'}

AREAS FOR IMPROVEMENT:
${result.weaknesses?.map((weakness: string, index: number) => `${index + 1}. ${weakness}`).join('\n') || 'No areas for improvement identified'}

RECOMMENDATIONS:
${result.recommendations?.map((rec: string, index: number) => `${index + 1}. ${rec}`).join('\n') || 'No recommendations available'}

KEYWORDS FOUND:
${result.keywords_found?.join(', ') || 'No keywords found'}

MISSING KEYWORDS:
${result.keywords_missing?.join(', ') || 'No missing keywords identified'}

Generated by TuneMyCV.com
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CV_Analysis_Report_${result.job_title || 'Report'}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-apple-core/20 via-white to-citrus/10 dark:from-blueberry/10 dark:via-gray-900 dark:to-citrus/5">
      <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <button
            onClick={onStartNew}
            className="flex items-center space-x-2 text-apricot hover:text-apricot/80 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Analyze Another CV</span>
          </button>
          <button 
            onClick={downloadPDF}
            className="flex items-center space-x-2 bg-apricot text-white px-4 py-2 rounded-md hover:bg-apricot/90 transition-colors"
          >
            <Download className="h-4 w-4" />
            <span>Download Report</span>
          </button>
        </div>

        {/* Main Score Card */}
        <div className={`bg-white dark:bg-blueberry/20 rounded-lg shadow-lg p-8 mb-8 border-2 ${getScoreBgColor(result.compatibility_score)}`}>
          <div className="text-center">
            <div className="flex items-center justify-center mb-4">
              <BarChart3 className={`h-8 w-8 ${getScoreColor(result.compatibility_score)} mr-2`} />
              <h1 className="text-2xl font-bold text-blueberry dark:text-citrus">CV Compatibility Analysis</h1>
            </div>
            {result.job_title && (
              <p className="text-lg text-blueberry/80 dark:text-apple-core mb-2">For: {result.job_title}</p>
            )}
            {result.company_name && result.company_name !== 'Company' && (
              <p className="text-md text-blueberry/70 dark:text-apple-core/80 mb-6">At: {result.company_name}</p>
            )}
            
            <div className="flex items-center justify-center mb-6">
              <div className="text-center">
                <div className={`text-6xl font-bold ${getScoreColor(result.compatibility_score)} mb-2`}>
                  {result.compatibility_score}%
                </div>
                <div className="text-blueberry/70 dark:text-apple-core/80">Compatibility Score</div>
              </div>
            </div>
            
            <Progress value={result.compatibility_score} className="w-full max-w-md mx-auto mb-4" />
            
            <div className="text-blueberry/70 dark:text-apple-core/80">
              {result.compatibility_score >= 70 && "Excellent match! Your CV aligns well with this position."}
              {result.compatibility_score >= 40 && result.compatibility_score < 70 && "Good potential! Some improvements could strengthen your application."}
              {result.compatibility_score < 40 && "Room for improvement. Consider tailoring your CV more specifically."}
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-8">
          {/* Executive Summary */}
          <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 border border-apple-core/20 dark:border-citrus/20">
            <div className="flex items-center mb-4">
              <Star className="h-5 w-5 text-apricot mr-2" />
              <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Executive Summary</h2>
            </div>
            <p className="text-blueberry/80 dark:text-apple-core">{result.executive_summary}</p>
          </div>

          {/* Quick Stats */}
          <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 border border-apple-core/20 dark:border-citrus/20">
            <h2 className="text-xl font-semibold text-blueberry dark:text-citrus mb-4">Quick Stats</h2>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-blueberry/70 dark:text-apple-core/80">Keywords Found:</span>
                <span className="font-semibold text-green-600">{result.keywords_found?.length || 0}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-blueberry/70 dark:text-apple-core/80">Keywords Missing:</span>
                <span className="font-semibold text-red-600">{result.keywords_missing?.length || 0}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-blueberry/70 dark:text-apple-core/80">Analysis Date:</span>
                <span className="font-semibold text-blueberry dark:text-citrus">{new Date(result.created_at).toLocaleDateString()}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Strengths and Weaknesses */}
        <div className="grid md:grid-cols-2 gap-6 mb-8">
          <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 border border-apple-core/20 dark:border-citrus/20">
            <div className="flex items-center mb-4">
              <CheckCircle className="h-5 w-5 text-green-600 mr-2" />
              <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Strengths</h2>
            </div>
            {result.strengths && result.strengths.length > 0 ? (
              <ul className="space-y-2">
                {result.strengths.map((strength: string, index: number) => (
                  <li key={index} className="flex items-start">
                    <div className="w-2 h-2 bg-green-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <span className="text-blueberry/80 dark:text-apple-core">{strength}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-blueberry/60 dark:text-apple-core/60">No specific strengths identified.</p>
            )}
          </div>

          <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 border border-apple-core/20 dark:border-citrus/20">
            <div className="flex items-center mb-4">
              <AlertCircle className="h-5 w-5 text-yellow-600 mr-2" />
              <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Areas for Improvement</h2>
            </div>
            {result.weaknesses && result.weaknesses.length > 0 ? (
              <ul className="space-y-2">
                {result.weaknesses.map((weakness: string, index: number) => (
                  <li key={index} className="flex items-start">
                    <div className="w-2 h-2 bg-yellow-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <span className="text-blueberry/80 dark:text-apple-core">{weakness}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-blueberry/60 dark:text-apple-core/60">No specific areas for improvement identified.</p>
            )}
          </div>
        </div>

        {/* Keyword Analysis */}
        <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 mb-8 border border-apple-core/20 dark:border-citrus/20">
          <div className="flex items-center mb-4">
            <BarChart3 className="h-5 w-5 text-apricot mr-2" />
            <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Keyword Analysis</h2>
          </div>
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <h3 className="font-semibold text-green-600 mb-3 flex items-center">
                <CheckCircle className="h-4 w-4 mr-1" />
                Found Keywords
              </h3>
              {result.keywords_found && result.keywords_found.length > 0 ? (
                <div className="flex flex-wrap gap-2">
                  {result.keywords_found.slice(0, 10).map((keyword: string, index: number) => (
                    <span key={index} className="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm">
                      {keyword}
                    </span>
                  ))}
                </div>
              ) : (
                <p className="text-blueberry/60 dark:text-apple-core/60">No keywords found.</p>
              )}
            </div>
            <div>
              <h3 className="font-semibold text-red-600 mb-3 flex items-center">
                <XCircle className="h-4 w-4 mr-1" />
                Missing Keywords
              </h3>
              {result.keywords_missing && result.keywords_missing.length > 0 ? (
                <div className="flex flex-wrap gap-2">
                  {result.keywords_missing.slice(0, 10).map((keyword: string, index: number) => (
                    <span key={index} className="bg-red-100 text-red-800 px-3 py-1 rounded-full text-sm">
                      {keyword}
                    </span>
                  ))}
                </div>
              ) : (
                <p className="text-blueberry/60 dark:text-apple-core/60">No missing keywords identified.</p>
              )}
            </div>
          </div>
        </div>

        {/* Recommendations */}
        <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 mb-8 border border-apple-core/20 dark:border-citrus/20">
          <div className="flex items-center mb-4">
            <TrendingUp className="h-5 w-5 text-apricot mr-2" />
            <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Recommendations</h2>
          </div>
          {result.recommendations && result.recommendations.length > 0 ? (
            <ul className="space-y-3">
              {result.recommendations.map((recommendation: string, index: number) => (
                <li key={index} className="flex items-start">
                  <div className="w-6 h-6 bg-apricot/20 text-apricot rounded-full flex items-center justify-center text-sm font-semibold mr-3 mt-0.5 flex-shrink-0">
                    {index + 1}
                  </div>
                  <span className="text-blueberry/80 dark:text-apple-core">{recommendation}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-blueberry/60 dark:text-apple-core/60">No specific recommendations available.</p>
          )}
        </div>
      </div>
    </div>
  );
};

export default AnalysisResults;
