
import React from 'react';
import { ArrowLeft, Download, BarChart3, CheckCircle, XCircle, TrendingUp, Star, AlertCircle, Target, BookOpen, Users } from 'lucide-react';
import { Progress } from '@/components/ui/progress';

interface AnalysisResultsProps {
  result: any;
  onStartNew: () => void;
}

const AnalysisResults: React.FC<AnalysisResultsProps> = ({ result, onStartNew }) => {
  const getScoreColor = (score: number) => {
    if (score >= 70) return 'text-green-600';
    if (score >= 40) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getScoreBgColor = (score: number) => {
    if (score >= 70) return 'bg-green-50 border-green-200';
    if (score >= 40) return 'bg-yellow-50 border-yellow-200';
    return 'bg-red-50 border-red-200';
  };

  const downloadPDF = () => {
    // Create HTML content for PDF generation
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>CV Analysis Report</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
          .header { text-align: center; margin-bottom: 40px; }
          .score { font-size: 48px; font-weight: bold; color: #2563eb; text-align: center; margin: 20px 0; }
          .section { margin: 30px 0; }
          .section h2 { color: #1f2937; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
          .list-item { margin: 10px 0; padding: 10px; background-color: #f9fafb; border-left: 4px solid #3b82f6; }
          .keyword { display: inline-block; background-color: #dbeafe; color: #1e40af; padding: 4px 8px; margin: 2px; border-radius: 4px; font-size: 12px; }
          .missing-keyword { background-color: #fee2e2; color: #991b1b; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>CV Compatibility Analysis Report</h1>
          <p><strong>Job Title:</strong> ${result.job_title || 'Not specified'}</p>
          <p><strong>Company:</strong> ${result.company_name || 'Not specified'}</p>
          <p><strong>Analysis Date:</strong> ${new Date(result.created_at).toLocaleDateString()}</p>
          <div class="score">${result.compatibility_score}%</div>
          <p>Compatibility Score</p>
        </div>

        <div class="section">
          <h2>Executive Summary</h2>
          <p>${result.executive_summary || 'No summary available'}</p>
        </div>

        <div class="section">
          <h2>Strengths</h2>
          ${result.strengths?.map((strength: string) => `<div class="list-item">${strength}</div>`).join('') || '<p>No strengths identified</p>'}
        </div>

        <div class="section">
          <h2>Areas for Improvement</h2>
          ${result.weaknesses?.map((weakness: string) => `<div class="list-item">${weakness}</div>`).join('') || '<p>No areas for improvement identified</p>'}
        </div>

        <div class="section">
          <h2>Recommendations</h2>
          ${result.recommendations?.map((rec: string, index: number) => `<div class="list-item">${index + 1}. ${rec}</div>`).join('') || '<p>No recommendations available</p>'}
        </div>

        <div class="section">
          <h2>Keywords Found</h2>
          <div>
            ${result.keywords_found?.map((keyword: string) => `<span class="keyword">${keyword}</span>`).join('') || '<p>No keywords found</p>'}
          </div>
        </div>

        <div class="section">
          <h2>Missing Keywords</h2>
          <div>
            ${result.keywords_missing?.map((keyword: string) => `<span class="keyword missing-keyword">${keyword}</span>`).join('') || '<p>No missing keywords identified</p>'}
          </div>
        </div>

        <div style="margin-top: 60px; text-align: center; color: #6b7280; font-size: 14px;">
          <p>Generated by TuneMyCV.com</p>
        </div>
      </body>
      </html>
    `;

    // Create a new window and write the HTML content
    const printWindow = window.open('', '', 'width=800,height=600');
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      
      // Wait for content to load, then print
      printWindow.onload = () => {
        printWindow.print();
        printWindow.close();
      };
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-apple-core/20 via-white to-citrus/10 dark:from-blueberry/10 dark:via-gray-900 dark:to-citrus/5">
      <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <button
            onClick={onStartNew}
            className="flex items-center space-x-2 text-apricot hover:text-apricot/80 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Analyze Another CV</span>
          </button>
          <button 
            onClick={downloadPDF}
            className="flex items-center space-x-2 bg-apricot text-white px-4 py-2 rounded-md hover:bg-apricot/90 transition-colors"
          >
            <Download className="h-4 w-4" />
            <span>Download Report</span>
          </button>
        </div>

        {/* Main Score Card */}
        <div className={`bg-white dark:bg-blueberry/20 rounded-lg shadow-lg p-8 mb-8 border-2 ${getScoreBgColor(result.compatibility_score)}`}>
          <div className="text-center">
            <div className="flex items-center justify-center mb-4">
              <BarChart3 className={`h-8 w-8 ${getScoreColor(result.compatibility_score)} mr-2`} />
              <h1 className="text-2xl font-bold text-blueberry dark:text-citrus">CV Compatibility Analysis</h1>
            </div>
            {result.job_title && (
              <p className="text-lg text-blueberry/80 dark:text-apple-core mb-2">For: {result.job_title}</p>
            )}
            {result.company_name && result.company_name !== 'Company' && (
              <p className="text-md text-blueberry/70 dark:text-apple-core/80 mb-6">At: {result.company_name}</p>
            )}
            
            <div className="flex items-center justify-center mb-6">
              <div className="text-center">
                <div className={`text-6xl font-bold ${getScoreColor(result.compatibility_score)} mb-2`}>
                  {result.compatibility_score}%
                </div>
                <div className="text-blueberry/70 dark:text-apple-core/80">Compatibility Score</div>
              </div>
            </div>
            
            <Progress value={result.compatibility_score} className="w-full max-w-md mx-auto mb-4" />
            
            <div className="text-blueberry/70 dark:text-apple-core/80">
              {result.compatibility_score >= 70 && "Excellent match! Your CV aligns well with this position."}
              {result.compatibility_score >= 40 && result.compatibility_score < 70 && "Good potential! Some improvements could strengthen your application."}
              {result.compatibility_score < 40 && "Room for improvement. Consider tailoring your CV more specifically."}
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-8">
          {/* Executive Summary */}
          <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 border border-apple-core/20 dark:border-citrus/20">
            <div className="flex items-center mb-4">
              <Star className="h-5 w-5 text-apricot mr-2" />
              <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Executive Summary</h2>
            </div>
            <p className="text-blueberry/80 dark:text-apple-core">{result.executive_summary}</p>
          </div>

          {/* Quick Stats */}
          <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 border border-apple-core/20 dark:border-citrus/20">
            <h2 className="text-xl font-semibold text-blueberry dark:text-citrus mb-4">Quick Stats</h2>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-blueberry/70 dark:text-apple-core/80">Keywords Found:</span>
                <span className="font-semibold text-green-600">{result.keywords_found?.length || 0}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-blueberry/70 dark:text-apple-core/80">Keywords Missing:</span>
                <span className="font-semibold text-red-600">{result.keywords_missing?.length || 0}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-blueberry/70 dark:text-apple-core/80">Analysis Date:</span>
                <span className="font-semibold text-blueberry dark:text-citrus">{new Date(result.created_at).toLocaleDateString()}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Strengths and Weaknesses */}
        <div className="grid md:grid-cols-2 gap-6 mb-8">
          <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 border border-apple-core/20 dark:border-citrus/20">
            <div className="flex items-center mb-4">
              <CheckCircle className="h-5 w-5 text-green-600 mr-2" />
              <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Strengths</h2>
            </div>
            {result.strengths && result.strengths.length > 0 ? (
              <ul className="space-y-2">
                {result.strengths.map((strength: string, index: number) => (
                  <li key={index} className="flex items-start">
                    <div className="w-2 h-2 bg-green-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <span className="text-blueberry/80 dark:text-apple-core">{strength}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-blueberry/60 dark:text-apple-core/60">No specific strengths identified.</p>
            )}
          </div>

          <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 border border-apple-core/20 dark:border-citrus/20">
            <div className="flex items-center mb-4">
              <AlertCircle className="h-5 w-5 text-yellow-600 mr-2" />
              <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Areas for Improvement</h2>
            </div>
            {result.weaknesses && result.weaknesses.length > 0 ? (
              <ul className="space-y-2">
                {result.weaknesses.map((weakness: string, index: number) => (
                  <li key={index} className="flex items-start">
                    <div className="w-2 h-2 bg-yellow-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <span className="text-blueberry/80 dark:text-apple-core">{weakness}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-blueberry/60 dark:text-apple-core/60">No specific areas for improvement identified.</p>
            )}
          </div>
        </div>

        {/* Keyword Analysis */}
        <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 mb-8 border border-apple-core/20 dark:border-citrus/20">
          <div className="flex items-center mb-4">
            <BarChart3 className="h-5 w-5 text-apricot mr-2" />
            <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Keyword Analysis</h2>
          </div>
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <h3 className="font-semibold text-green-600 mb-3 flex items-center">
                <CheckCircle className="h-4 w-4 mr-1" />
                Found Keywords
              </h3>
              {result.keywords_found && result.keywords_found.length > 0 ? (
                <div className="flex flex-wrap gap-2">
                  {result.keywords_found.slice(0, 10).map((keyword: string, index: number) => (
                    <span key={index} className="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm">
                      {keyword}
                    </span>
                  ))}
                </div>
              ) : (
                <p className="text-blueberry/60 dark:text-apple-core/60">No keywords found.</p>
              )}
            </div>
            <div>
              <h3 className="font-semibold text-red-600 mb-3 flex items-center">
                <XCircle className="h-4 w-4 mr-1" />
                Missing Keywords
              </h3>
              {result.keywords_missing && result.keywords_missing.length > 0 ? (
                <div className="flex flex-wrap gap-2">
                  {result.keywords_missing.slice(0, 10).map((keyword: string, index: number) => (
                    <span key={index} className="bg-red-100 text-red-800 px-3 py-1 rounded-full text-sm">
                      {keyword}
                    </span>
                  ))}
                </div>
              ) : (
                <p className="text-blueberry/60 dark:text-apple-core/60">No missing keywords identified.</p>
              )}
            </div>
          </div>
        </div>

        {/* Recommendations */}
        <div className="bg-white dark:bg-blueberry/20 rounded-lg shadow p-6 mb-8 border border-apple-core/20 dark:border-citrus/20">
          <div className="flex items-center mb-4">
            <TrendingUp className="h-5 w-5 text-apricot mr-2" />
            <h2 className="text-xl font-semibold text-blueberry dark:text-citrus">Recommendations</h2>
          </div>
          {result.recommendations && result.recommendations.length > 0 ? (
            <ul className="space-y-3">
              {result.recommendations.map((recommendation: string, index: number) => (
                <li key={index} className="flex items-start">
                  <div className="w-6 h-6 bg-apricot/20 text-apricot rounded-full flex items-center justify-center text-sm font-semibold mr-3 mt-0.5 flex-shrink-0">
                    {index + 1}
                  </div>
                  <span className="text-blueberry/80 dark:text-apple-core">{recommendation}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-blueberry/60 dark:text-apple-core/60">No specific recommendations available.</p>
          )}
        </div>
      </div>
    </div>
  );
};

export default AnalysisResults;
