
// New PDF generation utility using react-pdf
// This replaces the old jsPDF-based PDFGenerator

export interface AnalysisData {
  id?: string;
  job_title?: string;
  company_name?: string;
  compatibility_score?: number;
  created_at?: string;
  executive_summary?: string;
  strengths?: string[];
  weaknesses?: string[];
  recommendations?: string[];
  [key: string]: any;
}

export const generateAnalysisPDFContent = (result: AnalysisData): string => {
  const analysisDate = result.created_at ? new Date(result.created_at).toLocaleDateString() : new Date().toLocaleDateString();
  
  let content = `CV COMPATIBILITY ANALYSIS REPORT\n\n`;
  
  // Position Details
  content += `POSITION DETAILS\n`;
  if (result.job_title) content += `Job Title: ${result.job_title}\n`;
  if (result.company_name && result.company_name !== 'Company') content += `Company: ${result.company_name}\n`;
  content += `Analysis Date: ${analysisDate}\n\n`;
  
  // Compatibility Score
  content += `COMPATIBILITY SCORE\n${result.compatibility_score || 0}%\n\n`;
  
  // Executive Summary
  if (result.executive_summary) {
    content += `EXECUTIVE SUMMARY\n${result.executive_summary}\n\n`;
  }
  
  // Strengths
  if (result.strengths && result.strengths.length > 0) {
    content += `STRENGTHS\n`;
    result.strengths.forEach((strength, index) => {
      content += `${index + 1}. ${strength}\n`;
    });
    content += `\n`;
  }
  
  // Areas for Improvement
  if (result.weaknesses && result.weaknesses.length > 0) {
    content += `AREAS FOR IMPROVEMENT\n`;
    result.weaknesses.forEach((weakness, index) => {
      content += `${index + 1}. ${weakness}\n`;
    });
    content += `\n`;
  }
  
  // Recommendations
  if (result.recommendations && result.recommendations.length > 0) {
    content += `RECOMMENDATIONS\n`;
    result.recommendations.forEach((rec, index) => {
      content += `${index + 1}. ${rec}\n`;
    });
  }
  
  content += `\n\nGenerated by TuneMyCV.com`;
  
  return content;
};

export const downloadAnalysisAsText = (result: AnalysisData) => {
  const content = generateAnalysisPDFContent(result);
  const fileName = `CV_Analysis_Report_${result.job_title || 'Report'}_${new Date().toISOString().split('T')[0]}.txt`;
  
  const blob = new Blob([content], { type: 'text/plain' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};
